"""create core tables users pets abc_logs insights

Revision ID: 4ce9b7d0e42d
Revises: 
Create Date: 2026-02-16 10:43:04.473207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ce9b7d0e42d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('subscription_tier', sa.String(length=20), server_default=sa.text("'free'"), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('pets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('species', sa.String(length=10), nullable=False),
    sa.Column('breed', sa.String(length=100), nullable=True),
    sa.Column('age_years', sa.Integer(), nullable=True),
    sa.Column('age_months', sa.Integer(), nullable=True),
    sa.Column('weight_lbs', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('sex', sa.String(length=10), server_default=sa.text("'unknown'"), nullable=False),
    sa.Column('is_neutered', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('temperament', postgresql.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('medical_notes', sa.String(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("sex IN ('male', 'female', 'unknown')", name='ck_pets_sex'),
    sa.CheckConstraint("species IN ('cat', 'dog')", name='ck_pets_species'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pets_user_id'), 'pets', ['user_id'], unique=False)
    op.create_table('abc_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('antecedent_category', sa.String(length=50), nullable=False),
    sa.Column('antecedent_tags', postgresql.ARRAY(sa.String(length=50)), nullable=False),
    sa.Column('antecedent_notes', sa.String(), nullable=True),
    sa.Column('behavior_category', sa.String(length=50), nullable=False),
    sa.Column('behavior_tags', postgresql.ARRAY(sa.String(length=50)), nullable=False),
    sa.Column('behavior_severity', sa.Integer(), nullable=False),
    sa.Column('behavior_notes', sa.String(), nullable=True),
    sa.Column('consequence_category', sa.String(length=50), nullable=False),
    sa.Column('consequence_tags', postgresql.ARRAY(sa.String(length=50)), nullable=False),
    sa.Column('consequence_notes', sa.String(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('other_pets_present', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint('behavior_severity BETWEEN 1 AND 5', name='ck_abc_logs_severity'),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_abc_logs_pet_occurred', 'abc_logs', ['pet_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_abc_logs_pet_id'), 'abc_logs', ['pet_id'], unique=False)
    op.create_index(op.f('ix_abc_logs_user_id'), 'abc_logs', ['user_id'], unique=False)
    op.create_table('insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('insight_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('abc_log_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('behavior_function', sa.String(length=20), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("behavior_function IS NULL OR behavior_function IN ('attention', 'escape', 'tangible', 'sensory')", name='ck_insights_function'),
    sa.CheckConstraint("insight_type IN ('pattern', 'function', 'correlation', 'recommendation')", name='ck_insights_type'),
    sa.CheckConstraint('confidence BETWEEN 0 AND 1', name='ck_insights_confidence'),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_insights_pet_unread', 'insights', ['pet_id', 'is_read'], unique=False)
    op.create_index(op.f('ix_insights_pet_id'), 'insights', ['pet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_insights_pet_id'), table_name='insights')
    op.drop_index('idx_insights_pet_unread', table_name='insights')
    op.drop_table('insights')
    op.drop_index(op.f('ix_abc_logs_user_id'), table_name='abc_logs')
    op.drop_index(op.f('ix_abc_logs_pet_id'), table_name='abc_logs')
    op.drop_index('idx_abc_logs_pet_occurred', table_name='abc_logs')
    op.drop_table('abc_logs')
    op.drop_index(op.f('ix_pets_user_id'), table_name='pets')
    op.drop_table('pets')
    op.drop_table('users')
    # ### end Alembic commands ###
